/* Generated by KondoLisp. Do not edit manually */
/* Timestamp: Sat May 29 03:25:56 JST 2010 */
#define	Fprint_char	0
#define	Fwrite	1
#define	Fplus	2
#define	Fminus	3
#define	Ftimes	4
#define	Fdivide	5
#define	Fremainder	6
#define	Feq	7
#define	Fequal	8
#define	Fcons	9
#define	Flist	10
#define	Fdebug_mode	11
#define	Fpin_mode	12
#define	Fdelay	13
#define	Fdigital_write	14
#define	Fdigital_read	15
#define	Fanalog_reference	16
#define	Fanalog_read	17
#define	Fanalog_write	18
