/* generated by front-end.scm. do not edit manually */

#define	Fprint_char	0
#define	Fwrite	1
#define	Fplus	2
#define	Fminus	3
#define	Ftimes	4
#define	Fdivide	5
#define	Fremainder	6
#define	Feq	7
#define	Fequal	8
#define	Fdebug_mode	9
#define	Fpin_mode	10
#define	Fdelay	11
#define	Fdigital_write	12
#define	Fdigital_read	13
#define	Fanalog_reference	14
#define	Fanalog_read	15
#define	Fanalog_write	16
