/* Generated by KondoLisp. Do not edit manually */
/* Timestamp: Thu May 27 13:46:51 JST 2010 */

#define	VM_DUMMY	0
#define	VM_EXIT	1
#define	VM_IVAL	2
#define	VM_IVAL_PUSH	3
#define	VM_VREF_PUSH	4
#define	VM_PUSH	5
#define	VM_POP	6
#define	VM_JMP	7
#define	VM_BIF	8
#define	VM_BIFN	9
#define	VM_PUSH_FRAME	10
#define	VM_FUNCALL	11
#define	VM_BIND	12
#define	VM_UNBIND	13
#define	VM_VREF	14
#define	VM_VSET	15
#define	VM_LT	16
#define	VM_GT	17
#define	VM_LE	18
#define	VM_GE	19
#define	VM_EQ	20
#define	VM_PLUS	21
#define	VM_MINUS	22
#define	VM_IVAL_LT	23
#define	VM_IVAL_GT	24
#define	VM_IVAL_LE	25
#define	VM_IVAL_GE	26
#define	VM_IVAL_EQ	27
#define	VM_IVAL_PLUS	28
#define	VM_IVAL_MINUS	29
#define	VM_CONS	30
#define	VM_IVAL_CONS	31
