/* generated by front-end.scm. do not edit manually */

#define	VM_EXIT	0
#define	VM_IVAL	1
#define	VM_IVAL_PUSH	2
#define	VM_VREF_PUSH	3
#define	VM_PUSH	4
#define	VM_POP	5
#define	VM_JMP	6
#define	VM_BIF	7
#define	VM_BIFN	8
#define	VM_PUSH_FRAME	9
#define	VM_FUNCALL	10
#define	VM_BIND	11
#define	VM_UNBIND	12
#define	VM_VREF	13
#define	VM_VSET	14
#define	VM_LT	15
#define	VM_GT	16
#define	VM_LE	17
#define	VM_GE	18
#define	VM_EQ	19
#define	VM_PLUS	20
#define	VM_MINUS	21
#define	VM_CONS	22
#define	VM_IVAL_CONS	23
